/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseEnrollmentResponse } from '../../models/api-response-enrollment-response';
import { EnrollmentRequest } from '../../models/enrollment-request';

export interface EnrollInCourse$Params {
      body: EnrollmentRequest
}

export function enrollInCourse(http: HttpClient, rootUrl: string, params: EnrollInCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseEnrollmentResponse>> {
  const rb = new RequestBuilder(rootUrl, enrollInCourse.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseEnrollmentResponse>;
    })
  );
}

enrollInCourse.PATH = '/enrollments/enroll';
