/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCertificateResponse } from '../../models/api-response-certificate-response';

export interface GetCertificate$Params {
  idCourse: string;
}

export function getCertificate(http: HttpClient, rootUrl: string, params: GetCertificate$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCertificateResponse>> {
  const rb = new RequestBuilder(rootUrl, getCertificate.PATH, 'get');
  if (params) {
    rb.path('idCourse', params.idCourse, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCertificateResponse>;
    })
  );
}

getCertificate.PATH = '/enrollments/certificate/{idCourse}';
