/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyCourseResponse } from '../../models/my-course-response';

export interface GetMyCourses$Params {
}

export function getMyCourses(http: HttpClient, rootUrl: string, params?: GetMyCourses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MyCourseResponse>>> {
  const rb = new RequestBuilder(rootUrl, getMyCourses.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MyCourseResponse>>;
    })
  );
}

getMyCourses.PATH = '/enrollments/my-courses';
