/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApicreateCourse$Params as ApicreateCourse$Params } from './fn/course/apicreate-course';
export { apicreateCourse as apicreateCourse } from './fn/course/apicreate-course';
export type { ApigetallCourse$Params as ApigetallCourse$Params } from './fn/course/apigetall-course';
export { apigetallCourse as apigetallCourse } from './fn/course/apigetall-course';
export type { ApidetailsCourse$Params as ApidetailsCourse$Params } from './fn/course/apidetails-course';
export { apidetailsCourse as apidetailsCourse } from './fn/course/apidetails-course';
export type { ApigetallCategory$Params as ApigetallCategory$Params } from './fn/category/apigetall-category';
export { apigetallCategory as apigetallCategory } from './fn/category/apigetall-category';
export type { ApicreateCategory$Params as ApicreateCategory$Params } from './fn/category/apicreate-category';
export { apicreateCategory as apicreateCategory } from './fn/category/apicreate-category';
export type { ApicreateUser$Params as ApicreateUser$Params } from './fn/user/apicreate-user';
export { apicreateUser as apicreateUser } from './fn/user/apicreate-user';
export type { ApigetallUser$Params as ApigetallUser$Params } from './fn/user/apigetall-user';
export { apigetallUser as apigetallUser } from './fn/user/apigetall-user';
export type { ApicreateLesson$Params as ApicreateLesson$Params } from './fn/lesson/apicreate-lesson';
export { apicreateLesson as apicreateLesson } from './fn/lesson/apicreate-lesson';
export type { ApilessonGetall$Params as ApilessonGetall$Params } from './fn/lesson/apilesson-getall';
export { apilessonGetall as apilessonGetall } from './fn/lesson/apilesson-getall';
