/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListUserResponse } from '../../models/api-response-list-user-response';

export interface SearchUsers$Params {
  name?: string;
  email?: string;
  role?: string;
}

export function searchUsers(http: HttpClient, rootUrl: string, params?: SearchUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListUserResponse>> {
  const rb = new RequestBuilder(rootUrl, searchUsers.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('email', params.email, {});
    rb.query('role', params.role, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListUserResponse>;
    })
  );
}

searchUsers.PATH = '/users/search';
