/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCourseProgressResponse } from '../../models/api-response-course-progress-response';
import { LessonProgressRequest } from '../../models/lesson-progress-request';

export interface SaveProgress$Params {
      body: LessonProgressRequest
}

export function saveProgress(http: HttpClient, rootUrl: string, params: SaveProgress$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCourseProgressResponse>> {
  const rb = new RequestBuilder(rootUrl, saveProgress.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCourseProgressResponse>;
    })
  );
}

saveProgress.PATH = '/learning/progress';
