/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { MyCourseResponse } from '../../../models/enrollment.model';


export interface ApiMyCourses$Params { }

export function apiMyCourses(http: HttpClient, rootUrl: string, params?: ApiMyCourses$Params, context?: HttpContext): Observable<StrictHttpResponse<MyCourseResponse[]>> {
  const rb = new RequestBuilder(rootUrl, apiMyCourses.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      const body = JSON.parse(r.body);
      const courses = Array.isArray(body) ? body : [body];
      return (r as HttpResponse<any>).clone({ body: courses }) as StrictHttpResponse<MyCourseResponse[]>;
    })
  );
}

apiMyCourses.PATH = '/enrollments/my-courses';
