/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { CertificateResponse } from '../../../models/learning.model';


export interface ApiCertificate$Params {
  idCourse: string;
  body?: any
}

export function apiCertificate(http: HttpClient, rootUrl: string, params: ApiCertificate$Params, context?: HttpContext): Observable<StrictHttpResponse<CertificateResponse[]>> {
  const rb = new RequestBuilder(rootUrl, apiCertificate.PATH, 'get');
  if (params) {
    rb.path('idCourse', params.idCourse, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: r.body as CertificateResponse[] }) as StrictHttpResponse<CertificateResponse[]>;
    })
  );
}

apiCertificate.PATH = '/enrollments/certificate/{idCourse}';
