/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { CourseResponse } from '../../../models/course.model';


export interface Apicoursesbyteacher$Params {
  teacherId: string;
      body?: any
}

export interface ApicoursesbyteacherApiResponse {
  response?: {
    type?: string;
    listMessage?: string[];
  };
  data?: CourseResponse[];
}

export function apicoursesbyteacher(http: HttpClient, rootUrl: string, params: Apicoursesbyteacher$Params, context?: HttpContext): Observable<StrictHttpResponse<ApicoursesbyteacherApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apicoursesbyteacher.PATH, 'get');
  if (params) {
    rb.path('teacherId', params.teacherId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: r.body as ApicoursesbyteacherApiResponse }) as StrictHttpResponse<ApicoursesbyteacherApiResponse>;
    })
  );
}

apicoursesbyteacher.PATH = '/courses/teacher/{teacherId}/withlessons';
