/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { CourseResponse } from '../../../models/course.model';


export interface ApidetailsCourse$Params {
  idCourse: string;
  body?: any
}

export interface ApidetailsCourseApiResponse {
  response?: {
    type?: string;
    listMessage?: string[];
  };
  data?: CourseResponse;
}

export function apidetailsCourse(http: HttpClient, rootUrl: string, params: ApidetailsCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<ApidetailsCourseApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apidetailsCourse.PATH, 'get');
  if (params) {
    rb.path('idCourse', params.idCourse, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: r.body as ApidetailsCourseApiResponse }) as StrictHttpResponse<ApidetailsCourseApiResponse>;
    })
  );
}

apidetailsCourse.PATH = '/courses/detail/{idCourse}';
