/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { CourseResponse } from '../../../models/course.model';


export interface ApigetallCourse$Params {
      body?: any
}

export function apigetallCourse(http: HttpClient, rootUrl: string, params?: ApigetallCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<CourseResponse[]>> {
  const rb = new RequestBuilder(rootUrl, apigetallCourse.PATH, 'get');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: r.body as CourseResponse[] }) as StrictHttpResponse<CourseResponse[]>;
    })
  );
}

apigetallCourse.PATH = '/courses/list';
