/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { CourseCardResponse } from '../../../models/course.model';


export interface PublicCourseCard$Params {
}

export interface PublicCourseCardApiResponse {
  response?: {
    type?: string;
    listMessage?: string[];
  };
  data?: CourseCardResponse[];
}

export function publicCourseCard(http: HttpClient, rootUrl: string, params?: PublicCourseCard$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicCourseCardApiResponse>> {
  const rb = new RequestBuilder(rootUrl, publicCourseCard.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: r.body as PublicCourseCardApiResponse }) as StrictHttpResponse<PublicCourseCardApiResponse>;
    })
  );
}

publicCourseCard.PATH = '/courses/publicCourses';
