/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCategoryResponse } from '../../models/api-response-category-response';
import { CategoryRequest } from '../../models/category-request';

export interface Insert$Params {
      body: CategoryRequest
}

export function insert(http: HttpClient, rootUrl: string, params: Insert$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, insert.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCategoryResponse>;
    })
  );
}

insert.PATH = '/categories/insert';
