/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListCategoryResponse } from '../../models/api-response-list-category-response';

export interface SearchCategories$Params {
  value: string;
}

export function searchCategories(http: HttpClient, rootUrl: string, params: SearchCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, searchCategories.PATH, 'get');
  if (params) {
    rb.path('value', params.value, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListCategoryResponse>;
    })
  );
}

searchCategories.PATH = '/categories/search/{value}';
