/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCourseResponse } from '../../models/api-response-course-response';

export interface DeleteCourse$Params {
  idCourse: string;
}

export function deleteCourse(http: HttpClient, rootUrl: string, params: DeleteCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCourseResponse>> {
  const rb = new RequestBuilder(rootUrl, deleteCourse.PATH, 'delete');
  if (params) {
    rb.path('idCourse', params.idCourse, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCourseResponse>;
    })
  );
}

deleteCourse.PATH = '/courses/delete/{idCourse}';
