/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListCourseResponse } from '../../models/api-response-list-course-response';

export interface FindByTeacher$Params {
  teacherId: string;
}

export function findByTeacher(http: HttpClient, rootUrl: string, params: FindByTeacher$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListCourseResponse>> {
  const rb = new RequestBuilder(rootUrl, findByTeacher.PATH, 'get');
  if (params) {
    rb.path('teacherId', params.teacherId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListCourseResponse>;
    })
  );
}

findByTeacher.PATH = '/courses/teacher/{teacherId}';
