sonar.host.url=http://localhost:9000
sonar.token=sqp_84add043305c7a2cdea98ce60cbbba76202e88a9

sonar.projectKey=appfront
sonar.projectName=appfront
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/app/api/**
sonar.coverage.exclusions=**/*.spec.ts,src/environments/**,src/main.ts,src/polyfills.ts,src/app/api/**,**/*.d.ts,**/*.html,**/*.css,src/app/page/catalogs/**,src/app/page/about/**,src/app/page/home/**,src/app/page/teachers/**,src/app/page/dashboard-sell/**,src/app/features/teacher/student/**,src/app/features/coursecard/**,src/app/features/lesson-list/**,src/app/features/student/certificates/**,src/app/features/admin/categories/**,src/app/features/admin/courses/**,src/app/features/admin/dashboard/**,src/app/features/admin/enrollments/**,src/app/features/student/learning/certificate-modal/**,src/app/features/teacher/lesson/**,src/app/features/teacher/profile/**,src/app/features/teacher/overview-teacher/**,src/app/layout/componet-principal/**,src/app/features/student/course/learning-course/**,src/app/features/student/learning/learnin-header/**,src/app/features/student/learning/lesson-sidebar/**,src/app/features/student/learning/lesson-resource/**,src/app/layout/auth-layout/**,src/app/features/student/profile/**,src/app/message/**,src/app/app.ts,src/app/core/utils/**,src/app/layout/sidebar/**,src/app/layout/header/**,src/app/features/teacher/course/course-getall/**,src/app/features/teacher/course/course-insert/**,src/app/features/teacher/course/lesson-insert/**,src/app/features/teacher/course/course-details/**,src/app/features/admin/users/admin-users/**
sonar.cpd.exclusions=**/*.html,**/*.css,src/app/features/admin/**,src/app/features/teacher/**,src/app/features/student/**,src/app/page/**

sonar.typescript.lcov.reportPaths=coverage/appfront/lcov.info
sonar.javascript.lcov.reportPaths=coverage/appfront/lcov.info
sonar.sourceEncoding=UTF-8