/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseConversationSummaryResponse } from '../../models/api-response-conversation-summary-response';
import { CreateConversationRequest } from '../../models/create-conversation-request';

export interface GetOrCreateConversation$Params {
      body: CreateConversationRequest
}

export function getOrCreateConversation(http: HttpClient, rootUrl: string, params: GetOrCreateConversation$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseConversationSummaryResponse>> {
  const rb = new RequestBuilder(rootUrl, getOrCreateConversation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseConversationSummaryResponse>;
    })
  );
}

getOrCreateConversation.PATH = '/messages/conversations';
