/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListMessageResponse } from '../../models/api-response-list-message-response';

export interface GetMessagesByConversation$Params {
  conversationId: string;
}

export function getMessagesByConversation(http: HttpClient, rootUrl: string, params: GetMessagesByConversation$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListMessageResponse>> {
  const rb = new RequestBuilder(rootUrl, getMessagesByConversation.PATH, 'get');
  if (params) {
    rb.path('conversationId', params.conversationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListMessageResponse>;
    })
  );
}

getMessagesByConversation.PATH = '/messages/conversations/{conversationId}';
