/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListConversationSummaryResponse } from '../../models/api-response-list-conversation-summary-response';

export interface GetMyConversations$Params {
}

export function getMyConversations(http: HttpClient, rootUrl: string, params?: GetMyConversations$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListConversationSummaryResponse>> {
  const rb = new RequestBuilder(rootUrl, getMyConversations.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListConversationSummaryResponse>;
    })
  );
}

getMyConversations.PATH = '/messages/conversations';
