/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { TeacherEnrollmentResponse } from '../../../models/teacher.model';


export interface ApiTeacherenrollmentsbycourse$Params {
  idCourse: string;
}

export function apiTeacherenrollmentsbycourse(http: HttpClient, rootUrl: string, params: ApiTeacherenrollmentsbycourse$Params, context?: HttpContext): Observable<StrictHttpResponse<TeacherEnrollmentResponse[]>> {
  const rb = new RequestBuilder(rootUrl, apiTeacherenrollmentsbycourse.PATH, 'get');
  if (params) {
    rb.path('idCourse', params.idCourse, {});
  }

  return http.request(
    rb.build({
      responseType: 'json',
      accept: 'application/json',
      context
    })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeacherEnrollmentResponse[]>;
    })
  );
}

apiTeacherenrollmentsbycourse.PATH = '/teacher/enrollments/{idCourse}';
