/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApicreateLesson$Params {
  body?: {
    'contenUrl'?: string;
    'courseId'?: string;
    'description'?: string;
    'files'?: Blob[];
    'isFree'?: string;
    'lessonOrder'?: string;
    'title'?: string;
    'type'?: string;
  }
}

export function apicreateLesson(http: HttpClient, rootUrl: string, params?: ApicreateLesson$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apicreateLesson.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apicreateLesson.PATH = '/lessons/insert';
