/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApideleteLesson$Params {
  idLesson: string;
}

export function apideleteLesson(http: HttpClient, rootUrl: string, params: ApideleteLesson$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, apideleteLesson.PATH, 'delete');
  if (params) {
    rb.path('idLesson', params.idLesson, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: r.body }) as StrictHttpResponse<any>;
    })
  );
}

apideleteLesson.PATH = '/lessons/delete/{idLesson}';
