/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LessonResponse } from '../../models/lesson-response';

export interface GetLessonsByTeacher$Params {
  teacherId: string;
}

export function getLessonsByTeacher(http: HttpClient, rootUrl: string, params: GetLessonsByTeacher$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LessonResponse>>> {
  const rb = new RequestBuilder(rootUrl, getLessonsByTeacher.PATH, 'get');
  if (params) {
    rb.path('teacherId', params.teacherId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LessonResponse>>;
    })
  );
}

getLessonsByTeacher.PATH = '/lessons/list/teacher/{teacherId}';
