/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListLessonResponse } from '../../models/api-response-list-lesson-response';

export interface SearchLessons$Params {
  value: string;
}

export function searchLessons(http: HttpClient, rootUrl: string, params: SearchLessons$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListLessonResponse>> {
  const rb = new RequestBuilder(rootUrl, searchLessons.PATH, 'get');
  if (params) {
    rb.path('value', params.value, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListLessonResponse>;
    })
  );
}

searchLessons.PATH = '/lessons/search/{value}';
