/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListTeacherEnrollmentResponse } from '../../models/api-response-list-teacher-enrollment-response';

export interface GetTeacherEnrollmentsByCourse$Params {
  idCourse: string;
}

export function getTeacherEnrollmentsByCourse(http: HttpClient, rootUrl: string, params: GetTeacherEnrollmentsByCourse$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListTeacherEnrollmentResponse>> {
  const rb = new RequestBuilder(rootUrl, getTeacherEnrollmentsByCourse.PATH, 'get');
  if (params) {
    rb.path('idCourse', params.idCourse, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListTeacherEnrollmentResponse>;
    })
  );
}

getTeacherEnrollmentsByCourse.PATH = '/teacher/enrollments/{idCourse}';
