/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { CourseProgressResponse } from '../../../models/learning.model';

export interface ApiSaveProgress$Params {
    body?: {
        'idLesson'?: string;
        'watchedPercentage'?: number;
        'lastPositionSeconds'?: number;
    }
}

export function apiSaveProgress(
    http: HttpClient,
    rootUrl: string,
    params?: ApiSaveProgress$Params,
    context?: HttpContext
): Observable<StrictHttpResponse<CourseProgressResponse>> {

    const rb = new RequestBuilder(rootUrl, apiSaveProgress.PATH, 'post');
    if (params) {
        rb.body(params.body, 'application/json');
    }

    return http.request(
        rb.build({ responseType: 'json', accept: 'application/json', context })
    ).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return r as StrictHttpResponse<CourseProgressResponse>;
        })
    );
}

apiSaveProgress.PATH = '/learning/progress';