/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateCourse$Params as CreateCourse$Params } from './fn/course/create-course';
export { createCourse as createCourse } from './fn/course/create-course';
export type { GetallCourse$Params as GetallCourse$Params } from './fn/course/getall-course';
export { getallCourse as getallCourse } from './fn/course/getall-course';
export type { GetallCategory$Params as GetallCategory$Params } from './fn/category/getall-category';
export { getallCategory as getallCategory } from './fn/category/getall-category';
export type { CreateCategory$Params as CreateCategory$Params } from './fn/category/create-category';
export { createCategory as createCategory } from './fn/category/create-category';
export type { CreateUser$Params as CreateUser$Params } from './fn/user/create-user';
export { createUser as createUser } from './fn/user/create-user';
export type { GetallUser$Params as GetallUser$Params } from './fn/user/getall-user';
export { getallUser as getallUser } from './fn/user/getall-user';
