/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCategoryResponse {
  creationDate?: string;
  description?: string;
  idCategory?: string;
  name?: string;
  totalCourses?: number;
}
