/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminEnrollmentResponse {
  courseTitle?: string;
  enrollmentDate?: string;
  idEnrollment?: string;
  progress?: number;
  status?: string;
  studentName?: string;
  teacherName?: string;
}
