/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUserResponse {
  email?: string;
  firstName?: string;
  idUser?: string;
  isActive?: boolean;
  lastName?: string;
  permissions?: Array<string>;
  registrationDate?: string;
  role?: string;
}
