/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCourseResponse {
  categoryName?: string;
  creationDate?: string;
  description?: string;
  idCourse?: string;
  price?: number;
  status?: string;
  teacherName?: string;
  title?: string;
  totalStudents?: number;
}
