/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseContentResponse } from '../models/course-content-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseCourseContentResponse {
  data?: CourseContentResponse;
  response?: GenericResponse;
}
