/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenericResponse } from '../models/generic-response';
import { UserResponse } from '../models/user-response';
export interface ApiResponseUserResponse {
  data?: UserResponse;
  response?: GenericResponse;
}
