/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminUserResponse } from '../models/admin-user-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListAdminUserResponse {
  data?: Array<AdminUserResponse>;
  response?: GenericResponse;
}
