/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseResponse } from '../models/course-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListCourseResponse {
  data?: Array<CourseResponse>;
  response?: GenericResponse;
}
