/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CertificateResponse } from '../models/certificate-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseCertificateResponse {
  data?: CertificateResponse;
  response?: GenericResponse;
}
