/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenericResponse } from '../models/generic-response';
import { LessonResponse } from '../models/lesson-response';
export interface ApiResponseLessonResponse {
  data?: LessonResponse;
  response?: GenericResponse;
}
