/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnrollmentResponse } from '../models/enrollment-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseEnrollmentResponse {
  data?: EnrollmentResponse;
  response?: GenericResponse;
}
