/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResponse } from '../models/category-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseCategoryResponse {
  data?: CategoryResponse;
  response?: GenericResponse;
}
