/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenericResponse } from '../models/generic-response';
import { MessageResponse } from '../models/message-response';
export interface ApiResponseListMessageResponse {
  data?: Array<MessageResponse>;
  response?: GenericResponse;
}
