/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminCategoryResponse } from '../models/admin-category-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListAdminCategoryResponse {
  data?: Array<AdminCategoryResponse>;
  response?: GenericResponse;
}
