/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConversationSummaryResponse } from '../models/conversation-summary-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListConversationSummaryResponse {
  data?: Array<ConversationSummaryResponse>;
  response?: GenericResponse;
}
