/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenericResponse } from '../models/generic-response';
import { TeacherEnrollmentResponse } from '../models/teacher-enrollment-response';
export interface ApiResponseListTeacherEnrollmentResponse {
  data?: Array<TeacherEnrollmentResponse>;
  response?: GenericResponse;
}
