/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminCourseResponse } from '../models/admin-course-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListAdminCourseResponse {
  data?: Array<AdminCourseResponse>;
  response?: GenericResponse;
}
