/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseProgressResponse } from '../models/course-progress-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseCourseProgressResponse {
  data?: CourseProgressResponse;
  response?: GenericResponse;
}
