/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseCardResponse } from '../models/course-card-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListCourseCardResponse {
  data?: Array<CourseCardResponse>;
  response?: GenericResponse;
}
