/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenericResponse } from '../models/generic-response';
export interface ApiResponseBoolean {
  data?: boolean;
  response?: GenericResponse;
}
