/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminEnrollmentResponse } from '../models/admin-enrollment-response';
import { GenericResponse } from '../models/generic-response';
export interface ApiResponseListAdminEnrollmentResponse {
  data?: Array<AdminEnrollmentResponse>;
  response?: GenericResponse;
}
