/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CertificateResponse {
  certificateId?: string;
  completionDate?: string;
  courseName?: string;
  studentName?: string;
  teacherName?: string;
  totalLessons?: number;
}
