/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseRequest {
  coverImage?: Blob;
  description?: string;
  idCategory?: string;
  idTeacher?: string;
  level?: string;
  price?: number;
  status?: string;
  title?: string;
}
