/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseCardResponse {
  categoryName?: string;
  coverImage?: string;
  description?: string;
  idCourse?: string;
  level?: string;
  price?: number;
  status?: string;
  teacherFullName?: string;
  title?: string;
  totalLessons?: number;
}
