/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseProgressResponse {
  courseCompleted?: boolean;
  idLesson?: string;
  lastPositionSeconds?: number;
  lessonCompleted?: boolean;
  totalProgress?: number;
  watchedPercentage?: number;
}
