/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LessonContentResponse } from '../models/lesson-content-response';
export interface CourseContentResponse {
  categoryName?: string;
  completed?: boolean;
  coverImage?: string;
  description?: string;
  idCourse?: string;
  lastAccess?: string;
  lessons?: Array<LessonContentResponse>;
  teacherFullName?: string;
  title?: string;
  totalLessons?: number;
  totalProgress?: number;
}
