/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateConversationRequest {
  courseId?: string;
  recipientId: string;
  type: 'DIRECT' | 'COURSE_SUPPORT';
}
