/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LessonRequest {
  adjunctFiles?: Array<Blob>;
  contenUrl?: string;
  courseId?: string;
  description?: string;
  durationMinutes?: number;
  free?: boolean;
  lessonOrder?: number;
  mainVideoFile?: Blob;
  title?: string;
  type?: string;
}
