/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LessonFileResponse } from '../models/lesson-file-response';
export interface LessonResponse {
  contentUrl?: string;
  courseId?: string;
  createdAt?: string;
  description?: string;
  durationMinutes?: number;
  files?: Array<LessonFileResponse>;
  idLesson?: string;
  isFree?: boolean;
  lessonOrder?: number;
  title?: string;
  type?: string;
}
