/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LessonFileResponse } from '../models/lesson-file-response';
export interface LessonContentResponse {
  completed?: boolean;
  completedAt?: string;
  contentUrl?: string;
  description?: string;
  durationMinutes?: number;
  files?: Array<LessonFileResponse>;
  free?: boolean;
  idLesson?: string;
  lastPositionSeconds?: number;
  lessonOrder?: number;
  title?: string;
  type?: string;
  watchedPercentage?: number;
}
