/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LessonProgressRequest {
  idLesson?: string;
  lastPositionSeconds?: number;
  watchedPercentage?: number;
}
