/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LessonFileResponse {
  fileName?: string;
  fileOrder?: number;
  fileType?: string;
  fileUrl?: string;
  idFile?: string;
}
