/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MyCourseResponse {
  categoryName?: string;
  completed?: boolean;
  coverImage?: string;
  description?: string;
  idCourse?: string;
  idEnrollment?: string;
  lastAccess?: string;
  teacherFullName?: string;
  title?: string;
  totalLessons?: number;
  totalProgress?: number;
}
