/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ParticipantSummaryResponse {
  email?: string;
  firstName?: string;
  idUser?: string;
  lastReadAt?: string;
  role?: 'ROLE_ADMIN' | 'ROLE_TEACHER' | 'ROLE_STUDENT';
  surName?: string;
}
