/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeacherEnrollmentResponse {
  completed?: boolean;
  courseImage?: string;
  courseTitle?: string;
  enrollmentDate?: string;
  idCourse?: string;
  idEnrollment?: string;
  idStudent?: string;
  lastAccess?: string;
  studentEmail?: string;
  studentFullName?: string;
  totalProgress?: number;
}
