/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  email: string;
  firstName?: string;
  lastName?: string;
  password: string;
  role: 'ROLE_ADMIN' | 'ROLE_TEACHER' | 'ROLE_STUDENT';
}
