/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  active?: boolean;
  email?: string;
  firstName?: string;
  idUser?: string;
  role?: 'ROLE_ADMIN' | 'ROLE_TEACHER' | 'ROLE_STUDENT';
  surName?: string;
}
